module.exports = [
  {
    id: 1,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    isApproved: true,
    listingStatus: "approved",
    listingManager: "admin",
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 2,
    title: "Fully Furnished with extra storage closets",
    description: "This is really good for people with many belongings to store away",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 3,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "sale",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 4,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "sale",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 5,
    title: "1 Bedroom with 2 baths",
    description: "The living room is very spacious and bright. Big enough for parties and social events. This is only available for 1 tenant",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 6,
    title: "Large 4 Bedroom for big family",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 7,
    title: "Secluded 2 bed near cockburn",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 8,
    title: "Room only - Behind IGA",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 9,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 10,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 11,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 12,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 13,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 14,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 15,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 16,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 17,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 18,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 19,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 20,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 1,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 21,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 2,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 22,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 2,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 23,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 2,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 24,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 2,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 25,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 2,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 26,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 2,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 27,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 2,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 28,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 2,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 29,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 2,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  },
  {
    id: 30,
    title: "Fresh New 2 Bedroom for share",
    description: "The living room is very spacious and bright. Big enough for parties and social events",
    listingType: "rent",
    adminId: 2,
    listingStatus: "approved",
    listingManager: "admin",
    isApproved: true,
    createdAt: "2021-05-28T15:36:56.200",
    updatedAt: "2021-08-28T13:40:02.200"
  }
];
